name: Add App Installers to Release

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set package version and name
      uses: brown-ccv/gh-actions/get-package-info@master
      id: package_info

    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run-script build

    # Build electron app package installers
    - name: package electron - linux
      if: startsWith(matrix.os, 'ubuntu')
      run: npm run package:linux

    # Upload installers to github release
    - name: Upload app to release - linux
      if: startsWith(matrix.os, 'ubuntu')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/installers/${{ steps.package_info.outputs.package_name }}_${{ steps.package_info.outputs.package_version }}_x64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
